### Send POST request with json body
POST http://localhost:8080/auth/partner
Content-Type: application/json


{
  "partnerId": "bsh6226",
  "password": "bsh6226",
  "partnerName" : "변상화",
  "businessId": 1234567890,
  "phoneNumber" : "01041589332"
}


### Send POST request with json body
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "id": "bsh6226",
  "password": "bsh6226"
}

### Send POST request with json body
POST http://localhost:8080/auth/partner
Content-Type: application/json

{
  "partnerId": "jjh6226",
  "password": "bsh6226",
  "partnerName" : "조정해",
  "businessId": 1234567890,
  "phoneNumber" : "01041589332"
}


### Send POST request with json body
POST http://localhost:8080/auth/user
Content-Type: application/json

{
  "userId": "sh6226",
  "password": "bsh6226",
  "userName" : "변상화",
  "phoneNumber" : "01041589332"
}

### Send POST request with json body
POST http://localhost:8080/auth/user
Content-Type: application/json

{
  "userId": "sh6226",
  "password": "bsh6226",
  "userName" : "조정해",
  "phoneNumber" : "01041589332"
}


