### Send POST request with json body
POST http://localhost:8080/api/auth/partner
Content-Type: application/json


{
  "partnerId": "partner123",
  "password": "partner123",
  "partnerName" : "partner123",
  "businessId": 1234567890,
  "phoneNumber" : "12345678900"
}


### Send POST request with json body
GET http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "id": "partner123",
  "password": "partner123"
}



### Send POST request with json body
POST http://localhost:8080/api/auth/user
Content-Type: application/json

{
  "userId": "user123",
  "password": "user123",
  "userName" : "user123",
  "phoneNumber" : "12345678900"
}


### Send POST request with json body
GET http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "id": "user123",
  "password": "user123"
}
