### Send POST request with json body
POST http://localhost:8080/api/reservation
Content-Type: application/json

{
  "userId": "user123",
  "storeId" : "twosome",
  "reservationTime": "2025-08-30T14:00"
}

### 예약상태변경
PATCH http://localhost:8080/api/reservation/e00KHwyM
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfUEFSVE5FUiIsInN1YiI6InBhcnRuZXIxMjMiLCJpYXQiOjE3Mzk5NDMyOTAsImV4cCI6MTczOTk0Njg5MH0.8NXnsDtWreBsePTln42Y1DO8soBmlSK7j8nhaKge0_kdK0ugQjcwA5Zsz2ojZzgMBOJX5-mtIeshYJPmf_FN-w

{
  "memberId": "partner123",
  "status": "REJECTED"
}


### Send POST request with json body
POST http://localhost:8080/reservations/listbyuser
Content-Type: application/json

{
  "userId" : "alexander1",
  "storeId" : "스타벅스동대문"
}

### Send Patch request with json body
PATCH http://localhost:8080/reservations/confirm
Content-Type: application/json

{
  "reservationId" : "00KoHfSn"
}