### Send POST request with json body
POST http://localhost:8080/store/partner/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9QQVJUTkVSIn1dfQ.8JJw82ubv8uaavYGpLHRhb1Rhao_tnbzmWksoKLyZZhmYyS3q4HIC3gekXrtAmMMwg6v7i0y5StUf1FTYUgo2w

{
  "storeId" : "투썸플레이스동대문",
  "address": "서울시동대문구용두동",
  "storeComment" : "청결한 매장"

}

### Send POST request with json body
POST http://localhost:8080/store
Content-Type: application/json

{
  "partnerId": "jjh6226",
  "storeId" : "스타벅스동대문",
  "address": "서울시동대문구용두동",
  "storeComment" : "청결한 매장"
}


### GET request with a
GET http://localhost:8080/stores/partnerId/partner1
Accept: application/json
