### Send POST request with json body
POST http://localhost:8080/api/store/partner/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfUEFSVE5FUiIsInN1YiI6InBhcnRuZXIxMjMiLCJpYXQiOjE3Mzk4Nzg3MTksImV4cCI6MTczOTg4MjMxOX0.pmHNzVjY6VA3N18YX4wzlDt3O8AH0KY5OJaTOWPFAniW8vBirVYwPrYICqSzDykwzalnFYsWb_BuMS90YYxDqQ

{
  "storeId" : "투썸플레이스동대문",
  "address": "서울시동대문구용두동",
  "storeComment" : "청결한 매장"

}



