### Send POST request with json body
POST http://localhost:8080/stores
Content-Type: application/json

{
  "partnerId": "bsh6226",
  "storeId" : "투썸플레이스동대문",
  "address": "서울시동대문구용두동",
  "storeComment" : "청결한 매장"

}

### Send POST request with json body
POST http://localhost:8080/stores
Content-Type: application/json

{
  "partnerId": "jjh6226",
  "storeId" : "스타벅스동대문",
  "address": "서울시동대문구용두동",
  "storeComment" : "청결한 매장"
}



### GET request with a
GET http://localhost:8080/stores/partnerId/partner1
Accept: application/json
